# Generated by Django 4.0.2 on 2022-02-03 22:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(help_text='Nome da Empresa', max_length=50)),
                ('cnpj', models.CharField(max_length=14)),
            ],
        ),
    ]
